{
 "title": "Scalable service dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Count of all calls / min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(template_scalable_service_call_total[1m])*60",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Count of 'service' calls / min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(template_scalable_service_count_service_total[1m])*60",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage*100", "legendFormat": "{{pod}} ({{instance}})" }
   ]
  },
  {
   "title": "Average execution times of 'service' calls",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "template_scalable_service_avgexecutiontime_service_ms",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{container=\"scalable-service\"}*100",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "JVM used memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{container=\"scalable-service\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Tomcat threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{container=\"scalable-service\"}",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  { "title": "Pod parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{pod=\"$pod\"}*100",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "JVM used memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"scalable-service\", pod=\"$pod\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Tomcat threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{pod=\"$pod\"}",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  }
 ]
}