{
 "title": "Tomcat, Hystrix, Hikari",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(pod)" } },
   { "name": "container", "label": "Container", "query": { "query": "label_values(container)" } },
   { "name": "event", "label": "Event", "query": { "query": "label_values(event)" } }
  ]
 },
 "panels": [
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat - Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(tomcat_threads_busy_threads{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}} - busy threads"
    }
   ]
  },
  {
   "title": "Hystrix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threadpool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max_over_time(hystrix_threadpool_threads_active_current_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]) > 0",
       "legendFormat": "active - {{pod}} - {{key}}"
      }
     ]
    },
    {
     "title": "Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum by (event, container, pod, group, key) (increase(hystrix_execution_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", event=~\"$event\"}[$__interval])) > 0",
       "legendFormat": "{{event}} - {{container}} - {{pod}} - {{group}} - {{key}}"
      }
     ]
    },
    {
     "title": "Circuit Breaker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "1 = an" }
     ],
     "targets": [
      {
       "expr": "hystrix_circuit_breaker_open{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"} > 0",
       "legendFormat": "{{container}} - {{pod}} - {{group}} - {{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(hikaricp_connections_active{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}} - Active"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(jvm_threads_live_threads{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])",
     "legendFormat": "Live Threads - {{pod}}"
    },
    {
     "expr": "max_over_time(jvm_threads_states_threads{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", state=\"runnable\"}[$__interval])",
     "legendFormat": "Running Threads - {{pod}}"
    }
   ]
  }
 ]
}