FROM adoptopenjdk/openjdk11
WORKDIR /usr/src/auth-service

RUN apt-get update && apt-get install -y mc

EXPOSE 8400

COPY ./dependencies ./
COPY ./spring-boot-loader ./
COPY ./snapshot-dependencies ./
COPY ./bin ./
COPY ./application ./

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
