#know-how:version-catalog

[versions]
aspectj = '1.9.22.1'
jackson = '2.17.2'
jsonwebtoken = '0.12.6'
junit = '5.11.4'
logback = '1.5.8'
mapstruct = '1.6.0'
springdoc = '2.6.0'
czhabarta = '3.2.1263'


[plugins]
ben-manes-versions = { id = 'com.github.ben-manes.versions', version = '0.51.0' }
habarta-typescript-generator = { id = 'cz.habarta.typescript-generator', version.ref = 'czhabarta' }
io-spring-dependency-management = { id = 'io.spring.dependency-management', version = '1.1.7' }
johnrengelman-shadow = { id = 'com.github.johnrengelman.shadow', version = '8.1.1' }
org-springframework-boot = { id = 'org.springframework.boot', version = '3.4.3' }
sonarqube = { id = 'org.sonarqube', version = '5.1.0.4882' }
thin-launcher = { id = 'org.springframework.boot.experimental.thin-launcher', version = '1.0.31.RELEASE' }


[libraries]
habarta-typescript-generator = { module = 'cz.habarta.typescript-generator:typescript-generator-core', version.ref = 'czhabarta' }
antlr4 = 'org.antlr:antlr4:4.13.2'
aspectj-rt = { module = 'org.aspectj:aspectjrt', version.ref = 'aspectj' }
aspectj-weaver = { module = 'org.aspectj:aspectjweaver', version.ref = 'aspectj' }
assertj = 'org.assertj:assertj-core:3.26.3'
bouncycastle-bcpkix = 'org.bouncycastle:bcpkix-jdk15on:1.70'
bouncycastle-bcprov = 'org.bouncycastle:bcprov-jdk15on:1.70'
caffeine = 'com.github.ben-manes.caffeine:caffeine:3.1.8'
commons-cli = 'commons-cli:commons-cli:1.9.0'
commons-codec = 'commons-codec:commons-codec:1.17.1'
commons-collections4 = 'org.apache.commons:commons-collections4:4.5.0-M2'
commons-io = 'commons-io:commons-io:2.16.1'
commons-lang3 = 'org.apache.commons:commons-lang3:3.16.0'
commons-text = 'org.apache.commons:commons-text:1.11.0'
dom4j = 'dom4j:dom4j:2.1.4'
dumbster = 'com.github.kirviq:dumbster:1.7.1'
glassfish-expressly = 'org.glassfish.expressly:expressly:5.0.0'
google-code-findbugs = 'com.google.code.findbugs:jsr305:3.0.2'
guava = 'com.google.guava:guava:33.3.0-jre'
hibernate-validator = 'org.hibernate:hibernate-validator:8.0.1.Final'
hierynomus-smbj = 'com.hierynomus:smbj:0.13.0'
integralblue = 'com.integralblue:log4jdbc-spring-boot-starter:2.0.0'
jackson-annotations = { module = 'com.fasterxml.jackson.core:jackson-annotations', version.ref = 'jackson' }
jackson-core = { module = 'com.fasterxml.jackson.core:jackson-core', version.ref = 'jackson' }
jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version.ref = 'jackson' }
jackson-dataformat-yaml = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml', version.ref = 'jackson' }
jackson-datatype-jsr310 = { module = 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310', version.ref = 'jackson' }
jakarta-activation-api = 'jakarta.activation:jakarta.activation-api:2.1.3'
jakarta-annotation-api = 'jakarta.annotation:jakarta.annotation-api:3.0.0'
jakarta-validation-api = 'jakarta.validation:jakarta.validation-api:3.1.0'
javax-jaxb-api = 'javax.xml.bind:jaxb-api:2.1'
javax-mail = 'com.sun.mail:javax.mail:1.6.2'
javax-mail-api = 'javax.mail:javax.mail-api:1.6.2'
jaxb-api = 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'
jaxb-core = 'com.sun.xml.bind:jaxb-core:4.0.5'
jaxb-runtime = 'org.glassfish.jaxb:jaxb-runtime:4.0.5'
jaxb-xjc = 'org.glassfish.jaxb:jaxb-xjc:4.0.5'
jaxws-api = 'jakarta.xml.ws:jakarta.xml.ws-api:4.0.2'
jaxws-rt = 'com.sun.xml.ws:jaxws-rt:4.0.3'
jaxws-tools = 'com.sun.xml.ws:jaxws-tools:4.0.3'
jcifs-ng = 'eu.agno3.jcifs:jcifs-ng:2.1.10'
jetbrains-annotations = 'org.jetbrains:annotations:24.1.0'
jimfs = 'com.google.jimfs:jimfs:1.3.0'
jsonwebtoken-api = { module = 'io.jsonwebtoken:jjwt-api', version.ref = 'jsonwebtoken' }
jsonwebtoken-impl = { module = 'io.jsonwebtoken:jjwt-impl', version.ref = 'jsonwebtoken' }
jsonwebtoken-jackson = { module = 'io.jsonwebtoken:jjwt-jackson', version.ref = 'jsonwebtoken' }
junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit' }
juniversalchardet = 'com.github.albfernandez:juniversalchardet:2.5.0'
jws-api = 'javax.jws:javax.jws-api:1.1'
keycloakbom = 'org.keycloak.bom:keycloak-adapter-bom:12.0.4'
liquibase-core = 'org.liquibase:liquibase-core:4.25.0'
log4j-log4j = 'log4j:log4j:1.2.17'
logback-classic = { module = 'ch.qos.logback:logback-classic', version.ref = 'logback' }
logback-core = { module = 'ch.qos.logback:logback-core', version.ref = 'logback' }
logstash-logback-encoder = 'net.logstash.logback:logstash-logback-encoder:7.2'
lombok = 'org.projectlombok:lombok:1.18.34'
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'mapstruct' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'mapstruct' }
mssql-jdbc = 'com.microsoft.sqlserver:mssql-jdbc:12.6.2.jre11'
openapi-api = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-api', version.ref = 'springdoc' }
openapi-ui = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-ui', version.ref = 'springdoc' }
opencsv = 'com.opencsv:opencsv:5.9'
pdfbox = 'org.apache.pdfbox:pdfbox:3.0.3'
pdfbox-fontbox = 'org.apache.pdfbox:fontbox:3.0.3'
reflections = 'org.reflections:reflections:0.10.2'
slf4j-api = 'org.slf4j:slf4j-api:2.0.15'
slf4j-log4j12 = 'org.slf4j:slf4j-log4j12:2.0.13'
smb-nio = 'ch.pontius.nio:smb-nio:0.13.0'
spring-cloud = 'org.springframework.cloud:spring-cloud-dependencies:2024.0.0'
#spvitamin = 'hu.perit.spvitamin:spvitamin-dependencies:3.4.3-1-RELEASE'
tika = 'org.apache.tika:tika-core:2.9.2'
tika-parsers-standard-package = 'org.apache.tika:tika-parsers-standard-package:2.9.2'
vandeseer-easytable = 'com.github.vandeseer:easytable:1.0.2'
querydsl-sql = 'com.querydsl:querydsl-sql:5.1.0'

[bundles]
jsonwebtoken = ["jsonwebtoken-api", "jsonwebtoken-impl", "jsonwebtoken-jackson"]
jaxws = ['jaxws-tools', 'jaxws-api', 'jaxb-api', 'jakarta-activation-api', 'jaxws-rt']
