apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: wstemplate
  labels:
    monitored: prometheus
spec:
  type: ClusterIP
  selector:
    component: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: wstemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth-service
  template:
    metadata:
      labels:
        component: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker-registry:5000/wstemplate-template-auth-service:1.0.18-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 80
              scheme: HTTP
            periodSeconds: 300
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /actuator/health/startup
              port: 80
              scheme: HTTP
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TEMPLATE_AUTH_SERVICE_OPTS
              value: -Dspring.profiles.active=k8s
            - name: PROTOCOL
              value: https
            - name: APP
              value: auth-service
            - name: NAMESPACE
              value: wstemplate
            - name: DOMAIN
              value: k8s-test.perit.local
