apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: wstemplate
  labels:
    monitored: prometheus
spec:
  type: ClusterIP
  selector:
    component: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: wstemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth-service
  template:
    metadata:
      labels:
        component: auth-service
    spec:
      containers:
      - name: auth-service
        image: docker-registry:5000/wstemplate-template-auth-service:1.0.6-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: TEMPLATE_AUTH_SERVICE_OPTS
          value: -Dspring.profiles.active=k8s
        - name: PROTOCOL
          value: https
        - name: APP
          value: auth-service
        - name: NAMESPACE
          value: wstemplate
        - name: DOMAIN
          value: k8s-test.perit.hu
