apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: wstemplate
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    component: pgadmin
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-volume-claim
  namespace: wstemplate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: wstemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pgadmin
  template:
    metadata:
      labels:
        component: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.0.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: peter.nagy@perit.hu
            - name: PGADMIN_DEFAULT_PASSWORD
              value: sa
          volumeMounts:
            - name: pgadmin-volume
              mountPath: /pgadmin
      volumes:
        - name: pgadmin-volume
          persistentVolumeClaim:
            claimName: pgadmin-volume-claim
