{
 "title": "Scalable service dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of all calls / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(template_scalable_service_call_total[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Count of 'service' calls / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(template_scalable_service_count_service_total[1m])*60"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_usage*100" }
   ]
  },
  {
   "title": "Average execution times of 'service' calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "template_scalable_service_avgexecutiontime_service_ms"
    }
   ]
  },
  {
   "title": "CPU usage (1)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"scalable-service-1:8420\"}*100"
    }
   ]
  },
  {
   "title": "CPU usage (2)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"scalable-service-2:8430\"}*100"
    }
   ]
  },
  {
   "title": "CPU usage (3)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"scalable-service-3:8440\"}*100"
    }
   ]
  },
  {
   "title": "JVM used memory (1)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"scalable-service-1:8420\"}"
    }
   ]
  },
  {
   "title": "JVM used memory (2)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"scalable-service-2:8430\"}"
    }
   ]
  },
  {
   "title": "JVM used memory (3)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"scalable-service-3:8440\"}"
    }
   ]
  }
 ]
}