#docker compose for local development

version: '3.6'

networks:
  back-tier-net:
    driver: bridge
  db-net:
    driver: bridge


services:

  #    #####################################################################################
  #    ldap:
  #    #####################################################################################
  #        container_name: wstemplate-dev-ldap
  #        image: petyaba/ldap
  #        restart: unless-stopped
  #        ports:
  #            - "10389:10389"
  #        networks:
  #            - back-tier-net


  #####################################################################################
  postgres:
    #####################################################################################                 
    container_name: wstemplate-dev-postgres
    image: postgres:17.2-alpine3.21
    shm_size: 4g
    environment:
      - POSTGRES_PASSWORD=sa
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back-tier-net
      - db-net


  #####################################################################################
  pgadmin:
    #####################################################################################                 
    container_name: wstemplate-dev-pgadmin
    image: dpage/pgadmin4:9.0.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=peter.nagy@perit.hu
      - PGADMIN_DEFAULT_PASSWORD=sa
    ports:
      - "5400:80"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - db-net
    #logging:
    #    driver: none

volumes:
  postgres:
  pgadmin:
