#docker compose for local development

version: '3.6'

networks:
  back-tier-net:
    driver: bridge
  db-net:
    driver: bridge


services:

  #    #####################################################################################
  #    ldap:
  #    #####################################################################################
  #        container_name: wstemplate-dev-ldap
  #        image: petyaba/ldap
  #        restart: unless-stopped
  #        ports:
  #            - "10389:10389"
  #        networks:
  #            - back-tier-net


  #####################################################################################
  postgres:
    #####################################################################################                 
    container_name: wstemplate-dev-postgres
    image: postgres:17.2-alpine3.21
    shm_size: 4g
    environment:
      - POSTGRES_PASSWORD=sa
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back-tier-net
      - db-net


  #####################################################################################
  pgadmin:
    #####################################################################################                 
    container_name: wstemplate-dev-pgadmin
    image: dpage/pgadmin4:9.0.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=peter.nagy@perit.hu
      - PGADMIN_DEFAULT_PASSWORD=sa
    ports:
      - "5400:80"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - db-net
    #logging:
    #    driver: none


#  #####################################################################################
#  gateway:
#    #####################################################################################
#    container_name: wstemplate-dev-gateway
#    image: wstemplate-template-gateway
#    environment:
#      - JAVA_OPTS=-DEUREKA_SERVER=http://discovery:8400/eureka -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#    ports:
#      - '8500:8500'
#      - '5503:5005'
#    networks:
#      - back-tier-net
#    hostname: 'gateway'
#
#
#  #####################################################################################
#  discovery:
#    #####################################################################################
#    container_name: wstemplate-dev-discovery
#    image: wstemplate-template-eureka
#    environment:
#      #agentlib for remote debugging
#      - JAVA_OPTS=-DEUREKA_SERVER=http://discovery:8400/eureka -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#      #- TEMPLATE_EUREKA_OPTS=-Dspring.profiles.active=docker
#      - EUREKA_ENVIRONMENT_PROFILE=dev
#    ports:
#      - '8400:8400'
#      - '5501:5005'
#    networks:
#      - back-tier-net
#    depends_on:
#      #- ldap
#      - postgres
#    hostname: 'discovery'


volumes:
  postgres:
  pgadmin:
